import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs, doc, getDoc } from 'firebase/firestore';
const app = initializeApp({apiKey:"AIzaSyC_b21wRYQNFmDYvOcAlcMmbqvRU1kAjVo",projectId:"liga-afas-a554c"});
const db = getFirestore(app);
const s = await getDocs(collection(db,'matchdays'));
console.log(s.size, s.docs.map(d=>d.id).slice(0,8).join(' , '));
const d0 = s.docs.find(d=>!d.id.startsWith('playoff'));
console.log(JSON.stringify(d0.data()).slice(0,600));
const p = await getDoc(doc(db,'matchdays_2026_2027','playoff-liga-cuartos'));
console.log('PO:',JSON.stringify(p.data()).slice(0,600));
process.exit(0);
